#!/bin/bash

rm -rf bin
mkdir bin
cp -r css bin
cp -r js bin
cp -r css.js bin
cp -r index.html bin

cd bin

r.js -o baseUrl=. paths.requireLib=js/require name=js/main include=requireLib out=js/require.js